### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by ne0ark** [Tripplesixty/BDInfoCLI#7]
It seems like various bugs were fixed in original version. Can you please merge them in here.

**Comment by Tripplesixty** [comment]
Sorry for the incredibly long delay, but this build is based on the core BDInfo 5.8 code base. There's been significant architectural changes to get this to work from the CLI and pulling from upstream wont be super clean. 

According to the change log this is all that changed in the 0.5.9 release:

> Version 0.5.9 by robena 
> I made a small update to BDInfo 0.5.8, replacing the old XP style Browse dialog with the new Vista one.

Please file any actual bugs that you find while using it.
